'use strict';
const el=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let records=new Map(),selected=0,currentRevision=0,dirty=false,history=[],saving=false;
const hostedOrigin='https://xuyuanpeng-71-day-journey.danyelxu.chatgpt.site';
if(location.hostname==='xudaniel.github.io')location.replace(hostedOrigin+'/shared.html');
async function api(path,options={}){
 const response=await fetch(path,{...options,cache:'no-store',credentials:'same-origin',headers:{'Content-Type':'application/json','X-Journey-Request':'1',...options.headers}});
 let data;try{data=await response.json();}catch{throw new Error('共享服务暂不可用，请稍后重试。');}
 if(!response.ok){const err=new Error(data.error||'请求失败');err.status=response.status;throw err;}return data;
}
function drawList(){el('stageList').innerHTML=itinerary.map((x,i)=>`<button type="button" data-index="${i}" aria-current="${i===selected}">${records.get(x.start)?.data.verified?'✓ ':''}${i+1}. ${esc(records.get(x.start)?.data.city||x.city)}<small>${esc(x.date)}</small></button>`).join('');el('stageList').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(dirty&&!confirm('此阶段有尚未保存的输入。放弃输入并切换阶段？'))return;selected=+b.dataset.index;loadForm();});}
function loadForm(){const base=itinerary[selected],record=records.get(base.start);currentRevision=record?.revision||0;const data=record?.data||{city:base.city,dateLabel:base.date,summary:base.summary,note:'',verified:false};el('stageHeading').textContent=`第 ${selected+1} 阶段 · ${base.city}`;el('stageWindow').textContent=`原计划：${base.start} — ${base.end}`;el('sharedDate').value=data.dateLabel;el('sharedCity').value=data.city;el('sharedSummary').value=data.summary;el('sharedNote').value=data.note;el('sharedVerified').checked=data.verified;dirty=false;el('formMessage').textContent='';drawList();loadHistory();}
async function loadHistory(){const key=itinerary[selected].start;try{const data=await api('/api/history?stage='+key);if(key!==itinerary[selected].start)return;history=data.history;el('history').innerHTML=history.length?history.map(x=>`<li>版本 ${x.revision} · ${x.action.startsWith('restore:')?'恢复历史版本':'更新安排'}<small>${esc(x.actor_email)} · ${esc(new Date(x.created_at).toLocaleString())}</small>${x.revision!==currentRevision?`<button type="button" class="button" data-revision="${x.revision}">恢复此版本</button>`:''}</li>`).join(''):'<li>尚无共享修改。首次保存后会生成版本记录。</li>';el('undoLatest').disabled=history.length===0;el('history').querySelectorAll('[data-revision]').forEach(b=>b.onclick=()=>restore(+b.dataset.revision));}catch(e){el('history').textContent=e.message;}}
async function refresh(initial=false){try{const data=await api('/api/state');records=new Map(data.stages.map(x=>[x.stage,x]));el('syncStatus').textContent='已同步 · '+new Date().toLocaleTimeString();if(initial||!dirty&&!saving){loadForm();}else{drawList();if((records.get(itinerary[selected].start)?.revision||0)!==currentRevision)el('formMessage').textContent='其他设备更新了此阶段。您的输入已保留；保存前请载入最新版本。';}}catch(e){el('syncStatus').textContent=navigator.onLine?e.message:'离线 · 共享内容需要联网，未保存输入仍保留在本页';if(e.status===401||e.status===403){records.clear();history=[];el('sharedForm').reset();el('history').textContent='';el('workspace').hidden=true;el('authGate').hidden=false;el('authMessage').textContent=e.message;el('signIn').hidden=false;}}}
async function save(payload){if(saving)return;const key=itinerary[selected].start;saving=true;document.querySelectorAll('.shared-grid input,.shared-grid textarea,.shared-grid button').forEach(x=>x.disabled=true);try{const data=await api('/api/stage',{method:'POST',body:JSON.stringify({stage:key,expectedRevision:currentRevision,...payload})});records.set(key,data.stage);dirty=false;currentRevision=data.stage.revision;loadForm();el('formMessage').textContent='已保存到共享空间，其他设备会自动获取更新。';}catch(e){el('formMessage').textContent=e.message;if(e.status===409)await refresh();}finally{saving=false;document.querySelectorAll('.shared-grid input,.shared-grid textarea,.shared-grid button').forEach(x=>x.disabled=false);el('undoLatest').disabled=history.length===0;}}
el('sharedForm').oninput=()=>{dirty=true;};
el('sharedForm').onsubmit=e=>{e.preventDefault();save({data:{city:el('sharedCity').value,dateLabel:el('sharedDate').value,summary:el('sharedSummary').value,note:el('sharedNote').value,verified:el('sharedVerified').checked}});};
el('loadLatest').onclick=()=>{if(dirty&&!confirm('载入最新版本会替换本页尚未保存的输入。继续？'))return;dirty=false;refresh(true);};
async function restore(revision){if(!confirm('将此阶段恢复到所选版本？现有版本仍保留在修改记录中。'))return;await save({restoreRevision:revision});}
el('undoLatest').onclick=()=>{if(history.length>1){restore(history[1].revision);}else if(history.length===1&&confirm('撤销首次共享修改，恢复原始安排？修改记录仍保留。')){const base=itinerary[selected];save({data:{city:base.city,dateLabel:base.date,summary:base.summary,note:'',verified:false}});}};
async function loadMembers(){try{const {members}=await api('/api/members');el('memberList').innerHTML=members.map((x,i)=>`<li>${esc(x.email)}<button class="button" data-member="${i}" type="button">移除</button></li>`).join('')||'<li>尚未添加协作者。</li>';el('memberList').querySelectorAll('button').forEach(b=>b.onclick=async()=>{const email=members[+b.dataset.member].email;if(!confirm(`移除 ${email} 的协作权限？`))return;try{await api('/api/members',{method:'DELETE',body:JSON.stringify({email})});loadMembers();}catch(e){el('memberMessage').textContent=e.message;}});}catch(e){el('memberMessage').textContent=e.message;}}
el('memberForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/members',{method:'POST',body:JSON.stringify({email:el('memberEmail').value})});el('memberEmail').value='';el('memberMessage').textContent='已加入协作名单。请自行分享本页链接。';loadMembers();}catch(e){el('memberMessage').textContent=e.message;}};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
window.addEventListener('online',()=>refresh());
async function startWorkspace(){try{const {user}=await api('/api/session');if(!user){el('authMessage').textContent='登录后可同步安排、共享备注，并查看修改记录。';el('signIn').hidden=false;return;}el('account').textContent=user.email;if(user.role==='visitor'){el('authMessage').textContent='请让行程所有者将您的登录邮箱加入协作名单：'+user.email;return;}el('authGate').hidden=true;el('workspace').hidden=false;el('memberPanel').hidden=user.role!=='owner';const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const i=itinerary.findIndex(x=>x.start<=today&&today<=x.end);selected=Math.max(0,i);await refresh(true);if(user.role==='owner')loadMembers();setInterval(()=>{if(!document.hidden)refresh();},15000);}catch(e){el('authMessage').textContent=e.message;}}
startWorkspace();
