import {uid,validateJourneyData,currentStage,effectiveStages,dayNumber,todayInZone,detectConflicts,relationshipSummary,findPossiblePeopleDuplicates,impactOfStageChange,applyStageChange,undoLastChange} from './core.mjs';
import {EncryptedStore,downloadEnvelope} from './storage.mjs';

const $=id=>document.getElementById(id), qa=s=>[...document.querySelectorAll(s)];
const seed=await fetch('./data/journey.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('行程数据加载失败');return r.json()});
const validation=validateJourneyData(seed);if(!validation.ok)throw new Error(validation.errors.join('\n'));
const store=new EncryptedStore();let state=null,pendingStage=null,pendingRestore=null,selectedPersonId=null;
const tripTz=seed.trip.timeZone;

function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function formatDate(v){if(!v)return'—';return new Intl.DateTimeFormat('zh-CN',{month:'short',day:'numeric',weekday:'short',timeZone:'UTC'}).format(new Date(v+'T12:00:00Z'));}
function toast(text,undo=false){const el=$('toast');el.innerHTML=esc(text)+(undo?' · <button id="toastUndo" style="border:0;background:transparent;color:white;text-decoration:underline">撤销</button>':'');el.classList.add('show');if(undo)$('toastUndo').onclick=async()=>{state=undoLastChange(state);await save('已撤销');renderAll();};clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),4200);}
async function save(message='已保存'){await store.save(state);toast(message);}

$('unlockForm').addEventListener('submit',async e=>{e.preventDefault();const password=$('vaultPassword').value;$('unlockStatus').textContent='正在解锁…';try{const result=await store.unlock(password);state=result.state;$('lockScreen').hidden=true;$('app').hidden=false;$('vaultPassword').value='';$('unlockStatus').textContent='';renderAll();if(result.created)toast('本机保险库已创建');}catch(err){$('unlockStatus').textContent=err.message;}});
$('lockButton').onclick=()=>{store.lock();state=null;$('app').hidden=true;$('lockScreen').hidden=false;$('vaultPassword').focus();};

qa('[data-nav]').forEach(btn=>btn.addEventListener('click',()=>navigate(btn.dataset.nav)));
function navigate(name){qa('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===name));qa('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));$('headerTitle').textContent={today:'今日',risks:'风险',people:'人脉',settings:'设置'}[name]||name;scrollTo({top:0,behavior:'smooth'});}
qa('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());

function renderAll(){renderToday();renderRisks();renderPeople();renderHistory();renderPersonOptions();}
function todayKey(){return todayInZone(tripTz);}
function renderToday(){const date=todayKey(),stage=currentStage(seed,state,date),n=dayNumber(seed,date),risks=detectConflicts(state);$('dayBadge').textContent=`DAY ${n||'—'} / 71`;$('todayDate').textContent=formatDate(date);$('todayCity').textContent=stage?.city||'行程之外';$('todaySummary').textContent=stage?.summary||'当前日期不在71天项目内';$('stageRange').textContent=stage?`${stage.start} — ${stage.end}`:'—';$('riskCount').textContent=risks.length;$('editStageButton').disabled=!stage;$('editStageButton').dataset.stageId=stage?.id||'';$('stageCard').innerHTML=stage?`<p class="eyebrow">${esc(stage.eyebrow)}</p><p><strong>${esc(stage.city)}</strong></p><p>${esc(stage.start)} → ${esc(stage.end)}</p><p>${esc(stage.summary)}</p>`:'<p>当前没有行程阶段。</p>';
  const items=[...(state.events||[]).filter(x=>x.date===date).map(x=>({...x,_type:'event',_time:x.start})),...(state.travel||[]).filter(x=>x.date===date).map(x=>({...x,_type:'travel',_time:x.departureTime}))].sort((a,b)=>(a._time||'99:99').localeCompare(b._time||'99:99'));
  $('todayCount').textContent=items.length?`${items.length} 项`:'暂无';$('todayAgenda').classList.toggle('empty-state',!items.length);$('todayAgenda').innerHTML=items.length?items.map(i=>`<article class="agenda-card"><div class="agenda-time">${esc(i._time||'待排')}</div><div><h3>${esc(i.title)}</h3><p>${i._type==='travel'?'交通':'事项'}${i.location?` · ${esc(i.location)}`:''}</p></div></article>`).join(''):'暂无手动事项';
  if(risks.length){$('topRiskWrap').hidden=false;renderRiskCard($('topRisk'),risks[0]);}else $('topRiskWrap').hidden=true;
}
function renderRiskCard(el,r){el.className=`risk-card ${r.level}`;el.innerHTML=`<span class="risk-label">${r.level==='critical'?'CRITICAL':r.level==='warning'?'WARNING':'INFO'}</span><h3>${esc(r.title)}</h3><p>${esc(r.detail)}</p><button class="text-button" data-risk-ignore="${esc(r.id)}">Keep anyway</button>`;el.querySelector('[data-risk-ignore]').onclick=()=>ignoreRisk(r);}
async function ignoreRisk(r){const reason=prompt('为什么保留这个安排？（可选）','');state.riskOverrides=[...(state.riskOverrides||[]),{riskId:r.id,reason:reason||'',at:new Date().toISOString()}];await save('已保留该安排');renderAll();}
function renderRisks(){const risks=detectConflicts(state),root=$('riskList');root.classList.toggle('empty-state',!risks.length);root.innerHTML=risks.length?'':'当前没有检测到执行冲突。';risks.forEach(r=>{const el=document.createElement('article');renderRiskCard(el,r);root.appendChild(el);});}

$('addEventButton').onclick=()=>{$('eventDate').value=todayKey();$('eventStart').value='10:00';$('eventEnd').value='11:00';$('eventDialog').showModal();};
$('eventForm').addEventListener('submit',async e=>{e.preventDefault();state.events.push({id:uid('event'),title:$('eventTitle').value.trim(),date:$('eventDate').value,start:$('eventStart').value,end:$('eventEnd').value,location:$('eventLocation').value.trim(),timeZone:$('eventTimeZone').value,personId:$('eventPerson').value||null});await save();$('eventForm').reset();$('eventDialog').close();renderAll();});
$('addTravelButton').onclick=()=>{$('travelDate').value=todayKey();$('travelDeparture').value='12:00';$('travelArrival').value='14:00';$('travelDialog').showModal();};
$('travelForm').addEventListener('submit',async e=>{e.preventDefault();state.travel.push({id:uid('travel'),title:$('travelTitle').value.trim(),mode:$('travelMode').value,date:$('travelDate').value,departureTime:$('travelDeparture').value,arrivalTime:$('travelArrival').value,from:$('travelFrom').value.trim(),to:$('travelTo').value.trim(),timeZone:$('travelTimeZone').value});await save();$('travelForm').reset();$('travelDialog').close();renderAll();});

$('editStageButton').onclick=()=>{const stage=effectiveStages(seed,state).find(s=>s.id===$('editStageButton').dataset.stageId);if(!stage)return;$('stageId').value=stage.id;$('stageCity').value=stage.city;$('stageStart').value=stage.start;$('stageEnd').value=stage.end;$('stageReason').value='';$('stageDialog').showModal();};
$('previewStageButton').onclick=()=>{try{const id=$('stageId').value,patch={city:$('stageCity').value.trim(),start:$('stageStart').value,end:$('stageEnd').value};const impact=impactOfStageChange(seed,state,id,patch);pendingStage={id,patch,reason:$('stageReason').value.trim(),impact};$('impactBody').innerHTML=`<div><span>事项</span><strong>${impact.counts.events}</strong></div><div><span>交通</span><strong>${impact.counts.travel}</strong></div><div><span>待办</span><strong>${impact.counts.actions}</strong></div><div><span>新增风险</span><strong>${Math.max(0,impact.newRisks)}</strong></div>`;$('stageDialog').close();$('impactDialog').showModal();}catch(err){alert(err.message);}};
$('applyStageButton').onclick=async()=>{if(!pendingStage)return;state=applyStageChange(seed,state,pendingStage.id,pendingStage.patch,pendingStage.reason);await store.save(state);$('impactDialog').close();renderAll();toast('行程已更新',true);pendingStage=null;};

function renderPersonOptions(){$('eventPerson').innerHTML='<option value="">不关联</option>'+(state?.people||[]).map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');}
$('addPersonButton').onclick=()=>{$('personForm').reset();$('personDialog').showModal();};
$('personForm').addEventListener('submit',async e=>{e.preventDefault();const candidate={id:uid('person'),name:$('personName').value.trim(),aliases:$('personAliases').value.split(',').map(s=>s.trim()).filter(Boolean),tags:$('personTags').value.split(',').map(s=>s.trim()).filter(Boolean),nextTouch:$('personNextTouch').value||null};const duplicates=findPossiblePeopleDuplicates(state,candidate);if(duplicates.length&&!confirm(`可能已有同一人物：${duplicates.map(d=>d.name).join('、')}。仍然新增？`))return;const orgName=$('personOrg').value.trim();if(orgName){let org=state.organizations.find(o=>o.name.toLowerCase()===orgName.toLowerCase());if(!org){org={id:uid('org'),name:orgName};state.organizations.push(org);}candidate.organizationId=org.id;}state.people.push(candidate);await save();$('personDialog').close();renderAll();});
$('peopleSearch').addEventListener('input',renderPeople);
function renderPeople(){if(!state)return;const q=$('peopleSearch').value.trim().toLowerCase(),people=state.people.filter(p=>{const org=state.organizations.find(o=>o.id===p.organizationId)?.name||'';return !q||[p.name,...(p.aliases||[]),org,...(p.tags||[])].join(' ').toLowerCase().includes(q)}),root=$('peopleList');root.classList.toggle('empty-state',!people.length);root.innerHTML=people.length?'':'还没有人物。先新增一个重要联系人。';people.forEach(p=>{const sum=relationshipSummary(state,p.id),org=state.organizations.find(o=>o.id===p.organizationId)?.name||'';const card=document.createElement('button');card.className='person-card';card.innerHTML=`<div style="text-align:left"><h3>${esc(p.name)}</h3><p>${esc(org||p.tags?.join(' · ')||'未分类')}</p><p>${sum.lastInteraction?`上次 ${esc(sum.lastInteraction.at.slice(0,10))}`:'暂无互动'} · ${p.nextTouch?`下次 ${esc(p.nextTouch)}`:'未设下次联系'}</p></div><div><span class="muted small">OPEN</span><div class="count">${sum.openLoops}</div></div>`;card.onclick=()=>openPerson(p.id);root.appendChild(card);});}
function openPerson(id){selectedPersonId=id;const sum=relationshipSummary(state,id),p=sum.person,org=state.organizations.find(o=>o.id===p.organizationId)?.name||'';$('personDetailName').textContent=p.name;$('personDetailBody').innerHTML=`<p class="muted">${esc(org||p.tags?.join(' · ')||'')}</p><div class="meta-grid"><div><span>Open loops</span><strong>${sum.openLoops}</strong></div><div><span>Next touch</span><strong>${esc(sum.nextTouch||'未设')}</strong></div></div><h3>Open Loops</h3><div class="loop-list">${[...sum.owed.map(a=>`<div class="loop">我负责 · ${esc(a.title)}</div>`),...sum.waiting.map(a=>`<div class="loop">等待对方 · ${esc(a.title)}</div>`)].join('')||'<p class="muted small">暂无</p>'}</div><h3 style="margin-top:22px">Timeline</h3><div class="timeline">${sum.timeline.map(i=>`<div class="timeline-item"><strong>${esc(i.text)}</strong><span>${esc(i.at?.replace('T',' ').slice(0,16)||'')}</span></div>`).join('')||'<p class="muted small">暂无互动记录</p>'}</div>`;if(!$('personDetailDialog').open)$('personDetailDialog').showModal();}
$('addInteractionButton').onclick=()=>{$('interactionAt').value=new Date().toISOString().slice(0,16);$('interactionText').value='';$('interactionDialog').showModal();};
$('interactionForm').addEventListener('submit',async e=>{e.preventDefault();state.interactions.push({id:uid('interaction'),personId:selectedPersonId,at:$('interactionAt').value,text:$('interactionText').value.trim()});await save();$('interactionDialog').close();openPerson(selectedPersonId);renderPeople();});
$('addOpenLoopButton').onclick=()=>{$('loopForm').reset();$('loopDue').value=todayKey();$('loopDialog').showModal();};
$('loopForm').addEventListener('submit',async e=>{e.preventDefault();state.actions.push({id:uid('action'),personId:selectedPersonId,title:$('loopTitle').value.trim(),status:$('loopStatus').value,dueDate:$('loopDue').value||null});await save();$('loopDialog').close();openPerson(selectedPersonId);renderPeople();});

$('backupButton').onclick=async()=>{const envelope=await store.makeBackup(),date=todayKey();downloadEnvelope(envelope,`71-day-backup-${date}.enc.json`);localStorage.setItem('71day-last-backup',envelope.createdAt);renderHistory();toast('加密备份已生成');};
$('restoreInput').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{const envelope=JSON.parse(await file.text()),preview=await store.previewBackup(envelope,store.password);pendingRestore=preview;const older=(preview.revision||0)<(state.revision||0);$('restoreBody').innerHTML=`<p><strong>备份时间：</strong>${esc(preview.updatedAt||'—')}</p><p><strong>Revision：</strong>${preview.revision}（当前 ${state.revision||0}）</p><div class="impact-grid"><div><span>人物</span><strong>${preview.counts.people}</strong></div><div><span>事项</span><strong>${preview.counts.events}</strong></div><div><span>交通</span><strong>${preview.counts.travel}</strong></div><div><span>历史</span><strong>${preview.counts.history}</strong></div></div>${older?'<p style="color:var(--danger)">这个备份比当前设备旧。只有你明确确认后才会覆盖当前状态。</p>':''}`;$('restoreConfirmButton').textContent=older?'仍然恢复旧备份':'恢复数据';$('restoreDialog').showModal();}catch(err){alert(err.message);}finally{e.target.value='';}});
$('restoreConfirmButton').onclick=async()=>{if(!pendingRestore)return;const older=(pendingRestore.revision||0)<(state.revision||0);if(older&&!confirm('确定要用较旧的备份覆盖当前状态吗？'))return;state=await store.restore(pendingRestore.incoming);$('restoreDialog').close();pendingRestore=null;renderAll();toast('备份已恢复');};
$('undoButton').onclick=async()=>{const next=undoLastChange(state);if(next===state){toast('没有可撤销的行程变更');return;}state=next;await save('已撤销最近一次变更');renderAll();};
function renderHistory(){if(!state)return;const root=$('historyList'),items=[...(state.history||[])].reverse().slice(0,20);root.classList.toggle('empty-state',!items.length);root.innerHTML=items.length?items.map(h=>`<article class="history-card"><div class="history-top"><strong>${h.type==='stage-change'?'行程修改':'变更'}</strong><span class="muted small">${esc((h.at||'').replace('T',' ').slice(0,16))}</span></div><p>${h.reason?esc(h.reason):'未填写原因'}${h.undoneAt?' · 已撤销':''}</p><p>${esc(JSON.stringify(h.after||{}))}</p></article>`).join(''):'还没有变更历史。';const last=localStorage.getItem('71day-last-backup');$('backupMeta').textContent=last?`上次备份：${last.replace('T',' ').slice(0,16)}`:'尚未创建备份';}

if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(()=>{});